package network;

public enum Operation {
	GET_PLAYER, GET_TEAM, GET_GROUP, GET_MATCH, 
	MATCHING_PLAYERS, MATCHING_TEAMS, MATCHING_GROUPS, MATCHING_MATCHES,
	ADD_PLAYER, REMOVE_PLAYER,
	UPDATE_PLAYER, UPDATE_TEAM, UPDATE_MATCH,
	
	CREATE_GROUPS
}